# Generated by Django 2.0.5 on 2018-05-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='value',
            name='value_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
