# Generated by Django 2.0.5 on 2018-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20180526_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value_name',
            field=models.CharField(max_length=50),
        ),
    ]
