# Generated by Django 2.0.5 on 2018-08-07 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='values',
            field=models.ManyToManyField(related_name='values', to='goals.Value'),
        ),
    ]
