# Generated by Django 2.1.4 on 2018-12-07 07:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('applied_id', models.AutoField(primary_key=True, serialize=False)),
                ('applied_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'applied_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'countries',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayCompanies',
            fields=[
                ('display_company_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_company_name', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'display_companies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DisplayTitles',
            fields=[
                ('display_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_job_title', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'display_titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpiredJobs',
            fields=[
                ('expired_id', models.AutoField(primary_key=True, serialize=False)),
                ('expired_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expired_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExternalUrls',
            fields=[
                ('external_url_id', models.AutoField(primary_key=True, serialize=False)),
                ('external_url', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'external_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobDescriptions',
            fields=[
                ('job_description_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_description', models.TextField()),
            ],
            options={
                'db_table': 'job_descriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_published', models.DateTimeField()),
                ('date_scraped', models.DateTimeField()),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LabeledJobs',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('apply_label', models.NullBooleanField()),
                ('apply_timestamp', models.DateTimeField(blank=True, null=True)),
                ('skill_focus', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'db_table': 'labeled_jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillFocuses',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_label', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'skill_focuses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SkillParagraphs',
            fields=[
                ('paragraph_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_paragraph_text', models.TextField()),
                ('skill_paragraph_added', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'skill_paragraphs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'urls',
                'managed': False,
            },
        ),
    ]
