FROM centos:7
MAINTAINER "Dmitry Berezovsky <dmitry.berezovsky@logicify.com>"

#ENV APPLICATION_DIR="/srv/application"


RUN yum update -y; yum clean all
RUN yum-builddep -y python; yum -y install make postgresql-devel gcc \
 libtiff-devel libjpeg-devel libzip-devel freetype-devel lcms2-devel libwebp-devel tcl-devel tk-devel \
 libxslt-devel libxml2-devel; yum clean all

ENV PYTHON_VERSION="3.6.0"

RUN mkdir /tmp/python-build && cd /tmp/python-build && \
  curl https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tgz > python.tgz && \
  tar xzf python.tgz && cd Python-$PYTHON_VERSION && \
  ./configure --prefix=/usr/local && make install && cd / && rm -rf /tmp/python-build

# Install locale
RUN localedef -v -c -i en_US -f UTF-8 en_US.UTF-8 || true
ENV LC_ALL "en_US.UTF-8"


RUN pip3 install --upgrade pip setuptools

# RUN mkdir $APPLICATION_DIR && chown -R app:app $APPLICATION_DIR && cd $APPLICATION_DIR

#USER app

#WORKDIR $APPLICATION_DIR


ENV SCRAPYD_DIRS     /etc/scrapyd \
                     /etc/scrapyd/eggs \
                     /etc/scrapyd/logs \
                     /etc/scrapyd/items \
                     /var/log/scrapyd \
                     /var/log/scrapyd/project \
                     /var/lib/scrapyd

#RUN pip3 install -U \
RUN pip3 install \
    scrapy \
    scrapyd \
    scrapyd-client \
    pillow \
    psycopg2 \
    boto \
    sqlalchemy \
    twisted \
    scrapy-fake-useragent


RUN mkdir -p ${SCRAPYD_DIRS}

ADD scrapyd.conf /etc/scrapyd/

# Adding the project
RUN mkdir /home/snew/
ADD . /home/snew/

EXPOSE 6800

WORKDIR /home/snew/
RUN python3 setup.py bdist_egg
RUN scrapyd &
RUN scrapyd-deploy --build dist/news-0.1-py3.6.egg

# CMD

# CMD sh run_server.sh
# CMD scrapyd &
CMD sh run_server.sh
#CMD scrapyd
# ENTRYPOINT scrapyd
# && scrapyd-deploy news_server -p news
# RUN scrapyd-deploy news_server -p news







#CMD ["/bin/bash"]

#VOLUME ["$APPLICATION_DIR"]
